### ISSUE TITLE
Version 0.70 not supported in Thunderbird 68.2.2

### ISSUE THREAD

**Issue by theopensourcerer** [tsolucio/cbThunderbird#6]
Can't install the latest version of the xpi into TB68.2.2.

**Comment by joebordes** [comment]
that is a temporal file that the team is working on, it is not ready for the latest version of TB

We are still working on it but it is a very low priority thing. I will make a release whenever it is ready

https://discussions.vtiger.com/discussion/188957/thunderbird-plugin-incompatible-wich-thunderbird-60

https://discussions.corebos.org/showthread.php?tid=1653
